release:
    name: Release
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Configure & Build
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
          cmake --build build
          cmake --install build --prefix dist
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**
